[tool.poetry]
name = "pycheck"
version = "0.5.0"
description = "A tool for property-based random testing (PBRT) for Python programs"
authors = ["Shin Saito <shinsa@jp.ibm.com>"]
license = "MIT"
readme = "README.md"
documentation = "README.md"
repository = "https://github.ibm.com/SHINSA/pycheck"

[tool.poetry.dependencies]
python = "^3.10"
hypothesis = "*"
pandas = "*"
dask = "*"
decorator = "*"
more-itertools = "*"
lark-parser = "*"
environs = "*"
humanize = "*"

[tool.poetry.dev-dependencies]
autopep8 = "*"
isort = "*"
pytest = "*"
mypy = "*"
pylint = "^2.12.2"

[tool.pylint.basic]
good-names = ["f", "g"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
